// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OctoDI.Web.Models.DatabaseModels;

#nullable disable

namespace OctoDI.Web.Migrations.InvoiceLoggingDb
{
    [DbContext(typeof(InvoiceLoggingDbContext))]
    [Migration("20251125114137_InitialInvoiceLoggingDb")]
    partial class InitialInvoiceLoggingDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OctoDI.Web.Models.DatabaseModels.InvoiceLog", b =>
                {
                    b.Property<int>("InvoiceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceLogId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvoiceLogId");

                    b.ToTable("InvoiceLogs");
                });

            modelBuilder.Entity("OctoDI.Web.Models.DatabaseModels.InvoiceRequestLog", b =>
                {
                    b.Property<int>("InvoiceRequestLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceRequestLogId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceLogId")
                        .HasColumnType("int");

                    b.Property<string>("RequestPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvoiceRequestLogId");

                    b.HasIndex("InvoiceLogId");

                    b.ToTable("InvoiceRequestLogs");
                });

            modelBuilder.Entity("OctoDI.Web.Models.DatabaseModels.InvoiceResponseLog", b =>
                {
                    b.Property<int>("InvoiceResponseLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceResponseLogId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceLogId")
                        .HasColumnType("int");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvoiceResponseLogId");

                    b.HasIndex("InvoiceLogId");

                    b.ToTable("InvoiceResponseLogs");
                });

            modelBuilder.Entity("OctoDI.Web.Models.DatabaseModels.InvoiceRequestLog", b =>
                {
                    b.HasOne("OctoDI.Web.Models.DatabaseModels.InvoiceLog", "InvoiceLog")
                        .WithMany("RequestLogs")
                        .HasForeignKey("InvoiceLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceLog");
                });

            modelBuilder.Entity("OctoDI.Web.Models.DatabaseModels.InvoiceResponseLog", b =>
                {
                    b.HasOne("OctoDI.Web.Models.DatabaseModels.InvoiceLog", "InvoiceLog")
                        .WithMany("ResponseLogs")
                        .HasForeignKey("InvoiceLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceLog");
                });

            modelBuilder.Entity("OctoDI.Web.Models.DatabaseModels.InvoiceLog", b =>
                {
                    b.Navigation("RequestLogs");

                    b.Navigation("ResponseLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
